### ISSUE TITLE
Factor out cmake for gRPC-based client libraries

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#12428]
# Background

- Our libraries' `CMakeLists.txt` are generated once by the scaffold generator, then maintained by hand.
- The `CMakeLists.txt` are mostly the same, up to the library name and the quickstart runner.
- Making sweeping changes across the cmake build files can be cumbersome for those who are IDE-challenged (me).
  - Issues like #5782 become easier

# Audit Methodology

Look at `eye_test.sh` from this commit: https://github.com/dbolduc/google-cloud-cpp/commit/ef20659c443ba29fb4a94549d02942abd9556e41

# Audit Results

96 libraries are just good. I made a note for 20 of the libraries. They are grouped into categories below.

## Actually fine
- channel
- containeranalysis 
- dlp

In these libraries, the changes are outside the common library functions. These
are things such as DOXYGEN_EXTRA_INCLUDES, or disabling a library for a given
compiler.

## Handwritten
- bigquery (samples. Also, it is in a separate .cmake file)
- bigtable
- iam (samples)
- pubsub
- spanner
- storage

These are too complicated. We will leave these alone for now.

## No versioned clients
- dialogflow_cx
- dialogflow_es

Some service dirs contain "", referencing the forwarding headers. We skip these
from the doxygen example path by checking: `if (NOT dir STREQUAL "") ...`. This
would incorrectly skip a directory that has samples in Dialogflow.

We can update the logic to check if the samples directory exists, instead.

## Extra PROTO_LIST
- asset

This has been handled in the PoC with an optional variable. https://github.com/googleapis/google-cloud-cpp/commit/b1c76b3eca4fbf90845ed06ef08aff97952fad95

## Extra proto library dependencies
- binaryauthorization
- contentwarehouse

These have cross-library proto dependencies.

We can add a variable for additional protos and add it to:
- google_cloud_cpp_doxygen_targets(...)
- google_cloud_cpp_add_pkgconfig(...)

## Extra argument to external_googleapis_install_pc(...)
- optimization

This is unnecessary. We can remove it. I sent #12425

## Protos compiled in external/googleapis/CMakeLists.txt
- iam
- logging
- monitoring
- speech
- texttospeech
- trace

See #8022 for more details. I will ask Carlos what's up. I would say it is a bug
that we are building these extra proto libraries (the service ones). I do not
think customers will be using these protos without using the corresponding
client libraries.

Like he says, we could leave some sort of interface libraries for the weirdly
named ones. (e.g. I think we call it `cloud_speech_protos`, but we would call it
`speech_protos` these days).

We would define these interface libraries in the library's CMakeLists outside of
the grpc library function.

## Scaffolding

The scaffolding also supports generating experimental libraries. We tend not to
use it. I think I would leave it alone, and add a
google_cloud_cpp_add_experimental_grpc_library(...) before refactoring the
scaffolding. Maybe. :shrug:

# Tasks

- [ ] Add cmake helper, and factor out a plain library. I will pick `kms`.
- [ ] Move the other 99 plain libraries.
- [ ] Add additional proto lists. Move `asset`.
- [ ] Support cross library proto dependencies. Move `binaryauthorization`, `contentwarehouse`.
- [ ] Modify the forwarding header samples check. Move `dialogflow_cx`, `dialogflow_es`.
- [ ] Add support for experimental targets. Simplify the scaffolding.
- [ ] Make a decision on the #8022 libraries.
  - [ ] If we decide to do the work, move them.
