### ISSUE TITLE
Universe Domain Support

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#13115]
Tracking Bug for all Universe Domain tasks

### Phase 1 Unblocking Service/Generator Work

- [ ] define `UniverseDomainOption` in an internal namespace
- [ ] define `UniverseDomainRetryPolicy` and `UniverseDomainRetryPolicyOption` in an internal namespace
- [ ] define and implement `DetermineServiceEndpoint`
- [ ] define and implement `ErrorCredentialsConfig`, update visitors, add factory function

### Phase 2 Service/Generator Work

- [ ] Modify generator stub factory function creation to call `DetermineServiceEndpoint`, check for failure, and create appropriate Error Auth/Credentials type when failure occurs
- [ ] Modify Bigtable stub factory functions to call `DetermineServiceEndpoint`, check for failure, and create appropriate Error Auth/Credentials type when failure occurs
- [ ] Modify PubSub stub factory functions to call `DetermineServiceEndpoint`, check for failure, and create appropriate Error Auth/Credentials type when failure occurs
- [ ] Modify PubSubLite stub factory functions to call `DetermineServiceEndpoint`, check for failure, and create appropriate Error Auth/Credentials type when failure occurs
- [ ] Modify Spanner stub factory functions to call `DetermineServiceEndpoint`, check for failure, and create appropriate Error Auth/Credentials type when failure occurs
- [ ] Modify Storage gRPC stub factory functions to call DetermineServiceEndpoint`, check for failure, and create appropriate Error Auth/Credentials type when failure occurs
- [ ] Modify Storage REST stub factory functions to call `DetermineServiceEndpoint`, check for failure, and create appropriate Error Auth/Credentials type when failure occurs
- [ ] Create new google_cloud_cpp_universe_domain lib containing `AddUniverseDomainOption` and `GetUniverseDomain` function stubs in an internal namespace
- [ ] Implement `AddUniverseDomainOption` function
- [ ] Implement `GetUniverseDomain` function

### Phase 3 Integration Tests/Documentation

- [ ] Set up pr/ci builds that execute against testing environment
- [ ] Add integration tests for Bigtable
- [ ] Add integration tests for PubSub
- [ ] Add integration tests for PubSubLite
- [ ] Add integration tests for Spanner
- [ ] Add integration tests for Storage (gRPC)
- [ ] Add integration tests for Storage  (REST)
- [ ] Add integration tests for Compute (to test generated REST service)
- [ ] Add integration tests for KMS (to test generated gRPC service)
- [ ] Add in-depth guide to using `UniverseDomain` in docs/ directory which refers to all the relevant code samples
- [ ] Add sample code for retrieving the `UniverseDomainOption` from an instance of a Connection
- [ ] Add sample code for creating a Client using `AddUniverseDomainOption` and checking the `UniverseDomainOption` value
- [ ] Add sample code for creating a Client using `AddUniverseDomainOption` without checking the `UniverseDomainOption` value
- [ ] Add sample code for creating a Client using `GetUniverseDomainOption`
- [ ] Add sample code for setting an explicit `UniverseDomainOption` used in Connection creation
- [ ] Add sample code for creating a custom `UniverseDomainRetryPolicy` and setting it the Options, along with using it with either `AddUniverseDomainOption` or `GetUniverseDomainOption`

### Phase 4 Make Universe Domain support available

- [ ] Promote `UniverseDomainOption`, `UniverseDomainRetryPolicy`, and `UniverseDomainRetryPolicyOption` out of its internal namespace
- [ ] Promote `AddUniverseDomainOption` and `GetUniverseDomain` functions out of their internal namespace
