### ISSUE TITLE
Avoid crashes in tracing wrappers for streams

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#14458]
## Background

This is a similar issue to #13724.

Some of our tracing wrappers can crash. They crash when we try to access server initial metadata (aka "headers"), but the `grpc::ClientContext` has not been used.

https://github.com/googleapis/google-cloud-cpp/blob/aa2d6c1c513a97a853a1bd2e960781d7ef214aae/google/cloud/internal/async_streaming_read_rpc_tracing.h#L92

The gRPC team tells us in practice that when one of these streams is started (i.e. `Start()` has been called), the `grpc::ClientContext` will have metadata available.

https://github.com/googleapis/google-cloud-cpp/blob/aa2d6c1c513a97a853a1bd2e960781d7ef214aae/google/cloud/internal/async_streaming_read_rpc_tracing.h#L45

## Testing

For example, the following test will crash at HEAD, but should not.

```cc
TEST(AsyncStreamingReadRpcTracing, UnstartedStreamShouldNotExtractMetadata) {
  auto span_catcher = testing_util::InstallSpanCatcher();

  {
    auto mock = std::make_unique<MockStream>();
    auto span = MakeSpan("span");
    auto context = std::make_shared<grpc::ClientContext>();
    TestedStream stream(context, std::move(mock), span);
  }

  auto spans = span_catcher->GetSpans();
  EXPECT_THAT(spans, ElementsAre(SpanNamed("span")));
}
```

We will also want a test like:

```cc
TEST(AsyncStreamingReadRpcTracing, StartedStreamShouldExtractMetadata) { ... }
```

To run the unit tests for `AsyncStreamingReadRpcTracing` with Bazel, we can say:

```sh
bazel test --test_output=all //google/cloud:internal_async_streaming_read_rpc_tracing_test
```

## Solution?

One fix is to keep using the `EndSpan(grpc::ClientContext, ...)` when the stream has been started successfully...

But use the `EndSpan()` overload without a `grpc::ClientContext` when the stream was not started successfully.

https://github.com/googleapis/google-cloud-cpp/blob/aa2d6c1c513a97a853a1bd2e960781d7ef214aae/google/cloud/internal/opentelemetry.h#L205-L207

## Tasks

The following classes all have the same problem:
- [ ] [`AsyncStreamingReadRpcTracing`](https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/internal/async_streaming_read_rpc_tracing.h)
- [ ] [`AsyncStreamingWriteRpcTracing`](https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/internal/async_streaming_write_rpc_tracing.h)
- [ ] [`AsyncReadWriteStreamingRpcTracing`](https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/internal/async_read_write_stream_tracing.h)
