### ISSUE TITLE
Use build system to drive integration tests and samples

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3489]
In `g-c-pp-spanner` and `g-c-cpp-pubsub` we use the build system (either CMake/CTest and/or Bazel) to drive the integration tests and examples. This makes it easier to add new integration tests, as one does not need to remember to add the test to some shell script.  Likewise, the examples are easier to implement, as only one `.cc` file is modified.

As an additional benefit, the tests execution can be parallelized, which reduces the overall CI cycle time.

I think we would do this in stages:

- [x] Change the integration test configuration to support better named environment variables.
- [x] Cleanup the Bigtable integration tests to require no parameters.
- [x] Cleanup the Storage integration tests to require no parameters.
- [x] ~For each example program, create a new `auto` example that runs all the examples in the required order.~ This is now tracked in #3523 and #3524
- [x] ~Change the Bigtable scripts to run this example instead of each individual example.~ This is now tracked in #3528
- [x] ~Change the Storage scripts to run this example instead of each individual example.~ This is now tracked in #3528 
- [x] Change the build scripts to:
  - [x] Exclude any test labeled `integration-test` from the unit test builds.
  - [x] Change all the integration tests and examples to be labeled `integration-test`.
- [x] The CMake build scripts run the integration tests against emulators. We need to change them to:
  - [x] Start the emulators and leave them running.
  - [x] Use CTest to run the tests labeled `integration-tests`
  - [x] Shutdown the emulators.
- [x] The Bazel build scripts only run the integration tests for one build, and only against production.
       We need to change them to use `Bazel` to run the tests labeled `integration-tests` passing all necessary environment variables.
- [ ] Remove the old scripts to run tests.
- [ ] Cleanup the old environment variables from the integration test configuration.

**Comment by coryan** [comment]
Planning to cleanup the storage integration tests command-line.

**Comment by coryan** [comment]
I had forgotten about #441. It might still be relevant.

**Comment by coryan** [comment]
I think the bugs in https://github.com/googleapis/google-cloud-cpp/issues/3523 capture all the issues here.

Closing this issue as it has become redundant.
