### ISSUE TITLE
GCB: need design/plan for which builds will hit production vs use emulator

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6221]
Some integration tests need to hit production. For some services we have emulators. Tests that hit production are (generally) slower, flakier, and may run into production quota issues.

Sanitizier builds need to execute code in order to be effective. Running unit tests is good, but running integration tests gives us more coverage. So possibly all the sanitizers need to run integration tests too.

The code coverage build needs to run integration tests in order to cover as much code as possible.

Auto-generated libraries will likely not have any emulators. Their integration tests and samples would run against production.

**We need a mini-design doc outlining what our testing strategy should be for integration tests**
This doc should answer:
- Which builds will run integration tests against production?
- Which builds will run integration tests against emulators? 

----
- [x] The mini-design doc is at go/cloud-cxx:integration-tests-2022q1, discussed and approved today
- [x] We need to create a GCB build testing against production (#8323)
- [x] We need to remove the integration tests from the Kokoro builds (#8339)
- [x] We need to add a GCB builds that runs only the quickstarts using production (#8342)
- [x] We need to run two quickstarts (`google/cloud/{storage,spanner}/quickstart`) in each of the Kokoro builds (#8344)
- [x] We need to stop running quickstarts when compiling against older versions of the libraries (#8345)

**Comment by coryan** [comment]
This is now done.  There are (as always) opportunities for improvement, e.g., maybe more refactoring of the powershell scripts, and maybe parallelizing the quickstart builds a bit more.  We will leave that for the future.
