### ISSUE TITLE
Tracking bug for generated libraries

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#7807]
## Update

This is closed, all the bugs can be found in the [All GCP Services have a GA library](https://github.com/googleapis/google-cloud-cpp/milestone/42) milestone.

## Instructions

This issue lists all the libraries we need to generate and/or hand-craft (as of 2022-01). It is mostly intended as a way to coordinate work. Before generating a library do these things:

- Convert the entry to a bug (GitHub has a handy button to do this)
- Assign the bug to yourself
- If you find that a library cannot be generated, say because the generator is missing features, or some other reason, then:
  - Document what these blockers are in the newly created bug
  - If you are not going to fix these immediately just release the newly created bug
- Follow the instructions in [`doc/contributor/howto-guide-adding-generated-libraries.md`](https://github.com/googleapis/google-cloud-cpp/blob/main/doc/contributor/howto-guide-adding-generated-libraries.md)
- If you find that a service already has a generated (or hand-crafted) library, then just mark it as done in this list.

## Library List

- [x] #7826
- [x] #7851
- [x] #7871
- [ ] #7900
- [x] #7916
- [x] #7980
- [x] #7816
- [x] #8003
- [ ] #8104
- [ ] #8175
- [ ] #8176
- [ ] #8177
- [ ] #7989
- [x] Cloud Bigtable API: `bigtable.googleapis.com`
- [x] Cloud Bigtable Admin API: `bigtableadmin.googleapis.com`
- [x] #7809
- [x] #8106
- [x] #7973
- [x] #7808
- [x] #7892
- [x] #8115
- [x] #8118
- [x] #8148
- [ ] #8134
- [x] #7921
- [x] #7813
- [ ] #8178
- [ ] #8179
- [x] #7894
- [x] #7811
- [x] #7944
- [x] Cloud Tasks API: `cloudtasks.googleapis.com`
- [x] #8160
- [x] #7869
- [ ] #7810
- [ ] #8180
- [ ] #7981
- [x] #8108
- [ ] #8181
- [x] #7889
- [ ] #8182
- [ ] #8174
- [ ] #7990
- [x] #8029
- [ ] #7976
- [x] #7903
- [ ] #8183
- [ ] #7988
- [x] #8020
- [x] #8010
- [x] Identity and Access Management (IAM) API: `iam.googleapis.com`
- [x] IAM Service Account Credentials API: `iamcredentials.googleapis.com`
- [ ] #8184
- [x] #7912
- [x] #7897
- [ ] #8185
- [ ] #7796 
- [ ] #8186
- [x] #8152
- [x] #8161
- [x] #8044
- [x] #7986
- [x] #7904
- [x] #7987
- [x] #7945
- [x] #7956
- [x] #8026
- [x] Cloud Pub/Sub API: `pubsub.googleapis.com`
- [x] Pub/Sub Lite API: `pubsublite.googleapis.com`
- [x] #7906
- [x] #8154
- [ ] #8023
- [x] #7971
- [x] Secret Manager API: `secretmanager.googleapis.com`
- [x] #8136
- [ ] #8132
- [x] #8082
- [x] #8046
- [x] #8081
- [x] #8034
- [x] Cloud Spanner API: `spanner.googleapis.com`
- [ ] #7991
- [x] Cloud Storage API: `storage.googleapis.com`
- [x] #7907
- [x] #8017
- [x] #8014
- [x] #7999
- [x] #7959
- [x] #7943
- [x] #7896
- [x] #7860
- [x] #7847
- [x] #7819
- [x] Workflow Executions API: `workflowexecutions.googleapis.com`
- [x] Workflows API: `workflows.googleapis.com`

**Comment by coryan** [comment]
This issue is no longer useful to track the remaining bugs. Closing.
